---
- hosts: generic_vm
  gather_facts: true
  become: true
  vars:
    # Disable FRR version will install latest stable version of FRR
    # frr_version: "10.1"
    frr_branch: "10"
  pre_tasks:
    - name: debug ansible_os_family
      debug:
        var: ansible_os_family

    - name: add ssh_key
      ansible.posix.authorized_key:
        user: clab
        state: present
        key: "{{ lookup('file', '/home/sp/.ssh/id_rsa.pub') }}"

    - name: Install packages
      apt:
        name:
          - htop
          - bmon
          - lldpd
          - tcpdump
          - mtr-tiny
        state: present
        cache_valid_time: 30
      when: ansible_facts["os_family"] == "Debian"

    - name: Set SELinux permissive
      ansible.posix.selinux:
        policy: "targeted"
        state: "permissive"
      when: ansible_facts["os_family"] == "RedHat"

    - name: Install epel-release
      dnf:
        name: epel-release
        state: present
      when: ansible_facts["os_family"] == "RedHat"

    - name: Install packages
      dnf:
        name:
          - htop
          - bmon
          - lldpd
          - tcpdump
          - mtr
        state: present
        update_cache: True
      when: ansible_facts["os_family"] == "RedHat"

    - name: Configure nmcli interfaces
      community.general.nmcli:
        type: ethernet
        conn_name: "{{ item }}"
        method6: link-local
        method4: link-local
        state: present
      loop: "{{ nm_connection_uplinks }}"
      when: ansible_facts["os_family"] == "RedHat"
      register: nmcli

    - name: Down nmcli interfaces
      community.general.nmcli:
        type: ethernet
        conn_name: "{{ item }}"
        state: down
      loop: "{{ nm_connection_uplinks }}"
      when: nmcli.changed

    - name: Up nmcli interfaces
      community.general.nmcli:
        type: ethernet
        conn_name: "{{ item }}"
        state: up
      loop: "{{ nm_connection_uplinks }}"
      when: nmcli.changed

  roles:
    - frr
